spring.application.name=FoodProject
spring.application.version=0.01
app.maximum-student=${APP_MAXIMUM_STUDENT}
app.course-default-duration=${APP_COURSE_DEFAULT_DURATION}
app.enabled=${APP_ENABLED}
app.allowed-countries=${APP_ALLOWED_COUNTRIES}
spring.jpa.properties.hibernate.default_schema=studentcourse
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=slmokbb123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
app.base-url=http://localhost:${server.port}

