spring.application.name=FoodProject
spring.application.version=0.01
app.maximum-student=100
app.course-default-duration=15.552.000.000
app.enabled=true
app.allowed-countries=AZE,TR,UK,USA
spring.jpa.properties.hibernate.default_schema=stundercourse
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
app.base-url=http://localhost:${server.port}

